services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  eureka:
    image: vitrais/eureka:latest        # если собирал сам — заменишь на свой
    container_name: eureka
    restart: unless-stopped
    build:
      context: C:/Users/Виктор/IdeaProjects/eureka
    ports:
      - "8761:8761"

  config-server:
    image: vitrais/config-server:latest
    container_name: config-server
    build:
      context: ./External_Configuration
    restart: unless-stopped
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    image: vitrais/user-service:latest
    container_name: user-service
    build:
      context: ./user-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
      - eureka
      - config-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    image: vitrais/notification-service:latest
    container_name: notification-service
    build:
      context: ./notification-service
    restart: unless-stopped
    depends_on:
      - kafka
      - eureka
      - config-server
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  pgdata: