name: springrunner-stack

services:
  postgres:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d usersdb"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [app-net]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/2181' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [app-net]



  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    depends_on:
      zookeeper: { condition: service_healthy }
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks: [app-net]

  eureka:
    build:
      context: ../Eureka
      dockerfile: Dockerfile
    container_name: eureka
    depends_on: []
    environment:
      SERVER_PORT: "8761"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    ports: ["8761:8761"]
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8761/actuator/health | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [app-net]

  server-config:
    build:
      context: ../Server_Config
      dockerfile: Dockerfile
    container_name: server-config
    depends_on:
      eureka: { condition: service_healthy }
    environment:
      SERVER_PORT: "8888"
      SPRING_PROFILES_ACTIVE: "native"
    volumes:
      - ../External_Configuration:/config-repo:ro
    ports: ["8888:8888"]
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8888/actuator/health | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [app-net]

  gateway:
    build: ../Gateway_API
    container_name: gateway
    depends_on:
      eureka: { condition: service_healthy }
      server-config: { condition: service_healthy }
    environment:
      SPRING_APPLICATION_NAME: gateway-api
      SPRING_CLOUD_CONFIG_URI: http://server-config:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES: "true"

    ports:
      - "8080:8080"
    networks:
      - app-net


  user-service:
    build: .
    container_name: user-service
    depends_on:
      postgres: { condition: service_healthy }
      kafka: { condition: service_healthy }
      eureka: { condition: service_healthy }
      server-config: { condition: service_healthy }
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_CLOUD_CONFIG_URI: http://server-config:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES: "true"
    ports:
      - "8081:8081"
    networks:
      - app-net


  notification-service:
    build: ../notification-service
    container_name: notification-service
    depends_on:
      kafka: { condition: service_healthy }
      eureka: { condition: service_healthy }
      server-config: { condition: service_healthy }
    environment:
      SPRING_APPLICATION_NAME: notification-service
      SPRING_CLOUD_CONFIG_URI: http://server-config:8888
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES: "true"
    ports:
      - "8082:8082"
    networks:
      - app-net

volumes:
  pgdata:
  kafkadata:
  zoodata:

networks:
  app-net:
    driver: bridge